import { HookTemplate } from "../types";

export const VIRAL_HOOK_TEMPLATES: HookTemplate[] = [
  {
    id: "cheat_sheet_curation",
    name: "1. The High-Signal Resource / Cheat Sheet",
    category: "cheat_sheet",
    hook: "7 tools/lessons that will save you 20 hours a week (bookmark this):",
    description: "Triggers massive Copy-Link / Bookmark probability (+20.0, 40x Like multiplier).",
    whyItWorks: "Readers instantly recognize reference utility and save it for future lookup.",
    targetMetric: "Copy Link (40x)",
    example: "7 AI tools that will save you 15 hours of engineering this week (bookmark this):\n\n1. Claude Code - terminal coding\n2. Bolt.new - instant prototypes\n3. Cursor - inline refactoring\n\nWhich one is in your daily workflow?",
  },
  {
    id: "contrarian_take",
    name: "2. The Contrarian Reality Check",
    category: "contrarian",
    hook: "Stop doing {CommonMistake}. Here is what the top 1% actually do in 2026:",
    description: "Triggers pattern interrupts and discussion replies (+5.0, 10x Like multiplier).",
    whyItWorks: "Challenges conventional wisdom, forcing people to pause and read the counter-argument.",
    targetMetric: "Replies (10x)",
    example: "Stop putting links in your main tweets.\n\nHere is what the X algorithm actually does when you post a link:\n\n- Dwell time drops by 65%\n- Open-link weight is only +0.2 (vs +20.0 for bookmark)\n\nInstead, put the link in tweet 2. Agree or disagree?",
  },
  {
    id: "curiosity_gap",
    name: "3. The 99% Knowledge Gap",
    category: "curiosity",
    hook: "99% of people don't know this {Subject} secret. The breakdown:",
    description: "Maximized post-clicks (+0.4) and dwell time (+0.004/s).",
    whyItWorks: "Creates an irresistible curiosity gap that can only be resolved by reading the full post.",
    targetMetric: "Dwell Time",
    example: "99% of developers don't know the exact math behind the X algorithm.\n\nHere is the exact scoring formula exported from the production Rust engine:\n\n• Copy link: +20.0\n• Reply: +5.0\n• Like: +0.5\n• Report: -234.0\n\nThe 3 rules to follow:",
  },
  {
    id: "case_study_teardown",
    name: "4. The Zero-to-One Case Study",
    category: "case_study",
    hook: "How {Subject} grew from $0 to $100k/mo with 0 ad spend (Full Teardown):",
    description: "High quote-tweet multiplier (+5.0, 10x) and dark-social DM shares (+5.0).",
    whyItWorks: "Proof-driven narrative with step-by-step breakdown creates high authority.",
    targetMetric: "Quotes (10x)",
    example: "How a solo founder scaled an open-source tool to 50k GitHub stars in 90 days (Full Teardown):\n\nPhase 1: Build in public on X\nPhase 2: Optimize hooks for copy-link shares\nPhase 3: Launch on Product Hunt\n\nHere is the exact playbook step-by-step:",
  },
  {
    id: "raw_vulnerability_story",
    name: "5. The Raw Story / Transformation Arc",
    category: "story",
    hook: "6 months ago I was {Struggle}. Today I {Achievement}. The 4 pivots:",
    description: "Triggers profile follows (+4.0, 8x) and empathetic reply chains (+5.0).",
    whyItWorks: "Human vulnerability builds instant emotional rapport and trust.",
    targetMetric: "Follows (8x)",
    example: "12 months ago my startup had 3 weeks of runway and $0 MRR.\n\nToday we crossed $50,000 MRR with 85% gross margins.\n\nThe 4 pivots that saved the company:",
  },
  {
    id: "how_i_blueprint",
    name: "6. The 'How I Built This' Revelation",
    category: "how_to",
    hook: "How I built a production-ready {Product} in 48 hours using {TechStack}:",
    description: "High bookmark rate (+20.0) and technical credibility.",
    whyItWorks: "Actionable engineering workflows that peers want to replicate.",
    targetMetric: "Copy Link (40x)",
    example: "How I built and deployed an algorithmic content optimizer in 24 hours:\n\n• Next.js 15 App Router\n• Bun runtime\n• Google Cloud Run\n• Tailwind Obsidian glassmorphism\n\nHere is the architecture breakdown:",
  },
  {
    id: "fomo_trend_jacking",
    name: "7. The Industry Shift / Breaking Trend",
    category: "fomo",
    hook: "The {Industry} landscape just changed forever. Here is what happened in the last 24h:",
    description: "High repost velocity (+1.0) and conversation magnetism (+5.0).",
    whyItWorks: "Fear of missing out drives fast consumption and shares into teams/chats.",
    targetMetric: "Quotes (10x)",
    example: "The recommendation algorithm landscape just shifted.\n\nX open-sourced its Phoenix transformer ranking engine and visibility rules.\n\nHere are the 5 biggest changes every creator must know:",
  },
  {
    id: "before_after_contrast",
    name: "8. The Visual Before vs. After",
    category: "before_after",
    hook: "Before: {BadState}\nAfter: {GoodState}\n\nThe 3 micro-tweaks that made all the difference:",
    description: "Exceptional dwell time (+0.004/s) and visual stopping power.",
    whyItWorks: "High-contrast juxtaposition forces the brain to analyze what caused the jump.",
    targetMetric: "Dwell Time",
    example: "Before: 300 impressions per post\nAfter: 150,000 impressions per post\n\nThe 3 micro-tweaks that flipped the algorithm:\n\n1. Replaced links with high-utility cheat sheets\n2. Hook formatted in first 7 words\n3. Ended with open-ended debate questions\n\nSteal this setup:",
  },
  {
    id: "unfair_advantage",
    name: "9. The Unfair Advantage / Stack Reveal",
    category: "advantage",
    hook: "My unfair advantage for {Outcome} that feels like a cheat code:",
    description: "Drives intense curiosity and profile conversions (+4.0).",
    whyItWorks: "Promises asymmetric leverage with minimal friction.",
    targetMetric: "Follows (8x)",
    example: "My unfair advantage for writing viral technical content:\n\nI audit every draft against the exact production weights from xai-org/x-algorithm.\n\nHere is how you can use the same framework:",
  },
  {
    id: "contrarian_question",
    name: "10. The Debate Sparker / Contrarian Question",
    category: "question",
    hook: "Why is everyone still doing {OutdatedMethod} when the data proves {NewMethod} wins?",
    description: "Triggers heated debate in replies (+5.0, 10x like power).",
    whyItWorks: "Invites domain experts to chime in and defend or agree with their perspective.",
    targetMetric: "Replies (10x)",
    example: "Why are founders still hiring $10k/mo marketing agencies when you can build a 100k audience on X organically in 90 days?\n\nWhat am I missing?",
  },
  {
    id: "warning_costly_mistake",
    name: "11. The Expensive Mistake Warning",
    category: "warning",
    hook: "If you are doing {Activity}, you are burning money/time without knowing it:",
    description: "Strong loss-aversion trigger holding reader dwell time.",
    whyItWorks: "Loss aversion is psychologically 2x stronger than gain seeking.",
    targetMetric: "Dwell Time",
    example: "If you are posting on X without understanding negative downrank penalties, you are sabotaging your reach.\n\n1 report = -234.0 points (~468 likes lost)\n1 mute = -58.8 points (~117 likes lost)\n\nHere is how to stay in the green zone:",
  },
  {
    id: "ultimate_curated_database",
    name: "12. The Curated Vault / Ultimate Database",
    category: "resource",
    hook: "I spent 100+ hours analyzing {Subject}. Here is the complete free vault:",
    description: "Maximum Share-via-Copy-Link (+20.0) and DM shares (+5.0).",
    whyItWorks: "Condenses massive effort into immediate zero-friction value for the reader.",
    targetMetric: "Copy Link (40x)",
    example: "I spent 50 hours studying the open-source X algorithm codebase so you don't have to.\n\nHere is the ultimate master-sheet of every scoring weight, boost, and penalty (save this):",
  },
];
